# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: the_arun
brief-intro: Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://avanathan.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: the_arun 
github_username: avanathan 
email: arun.avanathan@gmail.com
dribbble_username:

    description_footer: footer-arun

# comments
# two ways to comment, only choose one, and use your own short name
# short_name
duoshuo_shortname: #avanathan
disqus_shortname: the_arun


# Build settings
# markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6

theme: jekyll-theme-hacker